/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUsageRouteImport } from './routes/user.usage'
import { Route as UserStoryBuilderRouteImport } from './routes/user.story-builder'
import { Route as UserSettingsRouteImport } from './routes/user.settings'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserLiveInterviewRouteImport } from './routes/user.live-interview'
import { Route as UserHistoryRouteImport } from './routes/user.history'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as UserChatInterviewRouteImport } from './routes/user.chat-interview'
import { Route as UserBillingRouteImport } from './routes/user.billing'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminQuestionBankRouteImport } from './routes/admin.question-bank'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminInterviewsRouteImport } from './routes/admin.interviews'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAiUsageRouteImport } from './routes/admin.ai-usage'
import { Route as UserEvaluationIdRouteImport } from './routes/user.evaluation.$id'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminInterviewsIdRouteImport } from './routes/admin.interviews.$id'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsageRoute = UserUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => UserRoute,
} as any)
const UserStoryBuilderRoute = UserStoryBuilderRouteImport.update({
  id: '/story-builder',
  path: '/story-builder',
  getParentRoute: () => UserRoute,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserLiveInterviewRoute = UserLiveInterviewRouteImport.update({
  id: '/live-interview',
  path: '/live-interview',
  getParentRoute: () => UserRoute,
} as any)
const UserHistoryRoute = UserHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const UserChatInterviewRoute = UserChatInterviewRouteImport.update({
  id: '/chat-interview',
  path: '/chat-interview',
  getParentRoute: () => UserRoute,
} as any)
const UserBillingRoute = UserBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => UserRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionBankRoute = AdminQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInterviewsRoute = AdminInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiUsageRoute = AdminAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AdminRoute,
} as any)
const UserEvaluationIdRoute = UserEvaluationIdRouteImport.update({
  id: '/evaluation/$id',
  path: '/evaluation/$id',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminInterviewsIdRoute = AdminInterviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInterviewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/interviews': typeof AdminInterviewsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/user/billing': typeof UserBillingRoute
  '/user/chat-interview': typeof UserChatInterviewRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/history': typeof UserHistoryRoute
  '/user/live-interview': typeof UserLiveInterviewRoute
  '/user/profile': typeof UserProfileRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/story-builder': typeof UserStoryBuilderRoute
  '/user/usage': typeof UserUsageRoute
  '/admin/interviews/$id': typeof AdminInterviewsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/user/evaluation/$id': typeof UserEvaluationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/interviews': typeof AdminInterviewsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/user/billing': typeof UserBillingRoute
  '/user/chat-interview': typeof UserChatInterviewRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/history': typeof UserHistoryRoute
  '/user/live-interview': typeof UserLiveInterviewRoute
  '/user/profile': typeof UserProfileRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/story-builder': typeof UserStoryBuilderRoute
  '/user/usage': typeof UserUsageRoute
  '/admin/interviews/$id': typeof AdminInterviewsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/user/evaluation/$id': typeof UserEvaluationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/interviews': typeof AdminInterviewsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/user/billing': typeof UserBillingRoute
  '/user/chat-interview': typeof UserChatInterviewRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/history': typeof UserHistoryRoute
  '/user/live-interview': typeof UserLiveInterviewRoute
  '/user/profile': typeof UserProfileRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/story-builder': typeof UserStoryBuilderRoute
  '/user/usage': typeof UserUsageRoute
  '/admin/interviews/$id': typeof AdminInterviewsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/user/evaluation/$id': typeof UserEvaluationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/login'
    | '/pricing'
    | '/register'
    | '/user'
    | '/admin/ai-usage'
    | '/admin/dashboard'
    | '/admin/interviews'
    | '/admin/payments'
    | '/admin/question-bank'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/blog/$slug'
    | '/user/billing'
    | '/user/chat-interview'
    | '/user/dashboard'
    | '/user/history'
    | '/user/live-interview'
    | '/user/profile'
    | '/user/settings'
    | '/user/story-builder'
    | '/user/usage'
    | '/admin/interviews/$id'
    | '/admin/users/$id'
    | '/user/evaluation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/login'
    | '/pricing'
    | '/register'
    | '/user'
    | '/admin/ai-usage'
    | '/admin/dashboard'
    | '/admin/interviews'
    | '/admin/payments'
    | '/admin/question-bank'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/blog/$slug'
    | '/user/billing'
    | '/user/chat-interview'
    | '/user/dashboard'
    | '/user/history'
    | '/user/live-interview'
    | '/user/profile'
    | '/user/settings'
    | '/user/story-builder'
    | '/user/usage'
    | '/admin/interviews/$id'
    | '/admin/users/$id'
    | '/user/evaluation/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/login'
    | '/pricing'
    | '/register'
    | '/user'
    | '/admin/ai-usage'
    | '/admin/dashboard'
    | '/admin/interviews'
    | '/admin/payments'
    | '/admin/question-bank'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/blog/$slug'
    | '/user/billing'
    | '/user/chat-interview'
    | '/user/dashboard'
    | '/user/history'
    | '/user/live-interview'
    | '/user/profile'
    | '/user/settings'
    | '/user/story-builder'
    | '/user/usage'
    | '/admin/interviews/$id'
    | '/admin/users/$id'
    | '/user/evaluation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/usage': {
      id: '/user/usage'
      path: '/usage'
      fullPath: '/user/usage'
      preLoaderRoute: typeof UserUsageRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/story-builder': {
      id: '/user/story-builder'
      path: '/story-builder'
      fullPath: '/user/story-builder'
      preLoaderRoute: typeof UserStoryBuilderRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/live-interview': {
      id: '/user/live-interview'
      path: '/live-interview'
      fullPath: '/user/live-interview'
      preLoaderRoute: typeof UserLiveInterviewRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/history': {
      id: '/user/history'
      path: '/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof UserHistoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/chat-interview': {
      id: '/user/chat-interview'
      path: '/chat-interview'
      fullPath: '/user/chat-interview'
      preLoaderRoute: typeof UserChatInterviewRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/billing': {
      id: '/user/billing'
      path: '/billing'
      fullPath: '/user/billing'
      preLoaderRoute: typeof UserBillingRouteImport
      parentRoute: typeof UserRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/question-bank': {
      id: '/admin/question-bank'
      path: '/question-bank'
      fullPath: '/admin/question-bank'
      preLoaderRoute: typeof AdminQuestionBankRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interviews': {
      id: '/admin/interviews'
      path: '/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AdminInterviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-usage': {
      id: '/admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/admin/ai-usage'
      preLoaderRoute: typeof AdminAiUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/evaluation/$id': {
      id: '/user/evaluation/$id'
      path: '/evaluation/$id'
      fullPath: '/user/evaluation/$id'
      preLoaderRoute: typeof UserEvaluationIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/interviews/$id': {
      id: '/admin/interviews/$id'
      path: '/$id'
      fullPath: '/admin/interviews/$id'
      preLoaderRoute: typeof AdminInterviewsIdRouteImport
      parentRoute: typeof AdminInterviewsRoute
    }
  }
}

interface AdminInterviewsRouteChildren {
  AdminInterviewsIdRoute: typeof AdminInterviewsIdRoute
}

const AdminInterviewsRouteChildren: AdminInterviewsRouteChildren = {
  AdminInterviewsIdRoute: AdminInterviewsIdRoute,
}

const AdminInterviewsRouteWithChildren = AdminInterviewsRoute._addFileChildren(
  AdminInterviewsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAiUsageRoute: typeof AdminAiUsageRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInterviewsRoute: typeof AdminInterviewsRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQuestionBankRoute: typeof AdminQuestionBankRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiUsageRoute: AdminAiUsageRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInterviewsRoute: AdminInterviewsRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQuestionBankRoute: AdminQuestionBankRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface UserRouteChildren {
  UserBillingRoute: typeof UserBillingRoute
  UserChatInterviewRoute: typeof UserChatInterviewRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserHistoryRoute: typeof UserHistoryRoute
  UserLiveInterviewRoute: typeof UserLiveInterviewRoute
  UserProfileRoute: typeof UserProfileRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserStoryBuilderRoute: typeof UserStoryBuilderRoute
  UserUsageRoute: typeof UserUsageRoute
  UserEvaluationIdRoute: typeof UserEvaluationIdRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserBillingRoute: UserBillingRoute,
  UserChatInterviewRoute: UserChatInterviewRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserHistoryRoute: UserHistoryRoute,
  UserLiveInterviewRoute: UserLiveInterviewRoute,
  UserProfileRoute: UserProfileRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserStoryBuilderRoute: UserStoryBuilderRoute,
  UserUsageRoute: UserUsageRoute,
  UserEvaluationIdRoute: UserEvaluationIdRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
