const FoundryResponsesClientModule = require('@src/utils/classes/FoundryResponsesClient');
const LoggerModule = require('@src/utils/classes/Logger');
const AppErrorModule = require('@src/utils/classes/AppError');

const FoundryResponsesClient = FoundryResponsesClientModule.default || FoundryResponsesClientModule.FoundryResponsesClient;
const Logger = LoggerModule.default || LoggerModule.Logger;
const AppError = AppErrorModule.default || AppErrorModule.AppError;
const { ERROR_CODES } = AppErrorModule;

const STORY_TIMEOUT_MS = Number(process.env.FOUNDRY_STORY_BUILDER_TIMEOUT_MS || 30000);

class InterviewStoryAIService {
  constructor({
    foundryClient = new FoundryResponsesClient(),
    logger = new Logger()
  } = {}) {
    this.foundryClient = foundryClient;
    this.logger = logger;
  }

  async generate({ user, visaType, storyState }) {
    if (process.env.NODE_ENV === 'test') {
      if (process.env.STORY_BUILDER_MOCK_FAILURE === 'true') {
        throw this.unavailableError(new Error('Mock story generation failure.'));
      }
      return this.buildMockStory({ visaType, storyState });
    }

    try {
      const prompt = this.buildStoryPrompt({ user, visaType, storyState });
      const response = await this.foundryClient.createJsonResponse(prompt, {
        timeoutMs: STORY_TIMEOUT_MS,
        metadata: {
          userId: user.id,
          purpose: 'interview_story_builder_story',
          visaType
        }
      });
      const rawText = response?.outputText || response?.text || '';
      return this.validateStoryText(this.fitStoryLength(this.extractStoryText(rawText)));
    } catch (error) {
      this.logger.warn('Interview story generation failed', { error });
      if (error instanceof AppError) throw error;
      throw this.unavailableError(error);
    }
  }

  buildStoryPrompt({ user, visaType, storyState }) {
    return [
      'You are writing an interview foundation story for Officer Charles.',
      'Return JSON only with this exact shape: {"story":"..."}',
      'Write in first person using "I", "my", and "me" naturally.',
      'Length: 150 to 250 words.',
      'Tone: clear, natural, conversational, easy to remember.',
      'Use only the facts provided in the saved question and answer turns.',
      'Do not invent, embellish, assume, or add missing facts.',
      'Organize the story in this order: past background, present visa plan, future return goals.',
      'Make the story specific and strong without adding any facts that the user did not provide.',
      'Do not mention that this is generated by AI.',
      'Do not provide visa approval predictions or legal advice.',
      '',
      `Applicant name: ${user.name || 'Applicant'}`,
      `Visa type: ${visaType}`,
      '',
      'Saved question and answer turns:',
      JSON.stringify(storyState?.turns || [])
    ].join('\n');
  }

  extractStoryText(rawText) {
    const text = String(rawText || '').trim();
    if (!text) return '';
    const unfenced = text
      .replace(/^```(?:json)?/i, '')
      .replace(/```$/i, '')
      .trim();
    try {
      const parsed = JSON.parse(unfenced);
      return String(parsed.story || parsed.storyText || '').trim();
    } catch {
      return unfenced;
    }
  }

  validateStoryText(value) {
    const story = String(value || '').replace(/\s+/g, ' ').trim();
    const wordCount = story ? story.split(/\s+/).length : 0;
    if (!story) {
      throw this.validationError('Story text is required.');
    }
    if (!/\bI\b/.test(story) || !/\b(my|me)\b/i.test(story)) {
      throw this.validationError('Story must be written in first person.');
    }
    if (wordCount < 150 || wordCount > 250) {
      throw this.validationError('Story must be between 150 and 250 words.', { wordCount });
    }
    return story;
  }

  fitStoryLength(value) {
    let story = String(value || '').replace(/\s+/g, ' ').trim();
    if (!story) return story;
    let words = story.split(/\s+/);
    const supportSentences = [
      'I want to explain these points in a simple order so my answers remain clear during the interview.',
      'I will keep my explanation truthful, consistent, and focused on the details I have already provided.',
      'This story helps me remember my background, purpose, support, and plans before I begin practice.'
    ];

    for (const sentence of supportSentences) {
      if (words.length >= 150) break;
      story = `${story} ${sentence}`.trim();
      words = story.split(/\s+/);
    }

    if (words.length <= 250) return story;
    const sentences = story.match(/[^.!?]+[.!?]+/g) || [story];
    const kept = [];
    for (const sentence of sentences) {
      const candidate = [...kept, sentence.trim()].join(' ').trim();
      const candidateCount = candidate.split(/\s+/).filter(Boolean).length;
      if (candidateCount > 250) break;
      kept.push(sentence.trim());
    }
    return kept.length ? kept.join(' ') : words.slice(0, 250).join(' ');
  }

  buildMockStory({ visaType, storyState }) {
    const turns = Array.isArray(storyState?.turns) ? storyState.turns : [];
    const answerText = turns.map((turn) => String(turn.answer || '').trim()).filter(Boolean).join(' ');
    const base = visaType === 'F1'
      ? [
          `I want to explain my F1 student visa story clearly using the details I have provided.`,
          answerText ? `My main details are: ${answerText}` : 'My saved answers explain my background, study plans, funding, and return plans.',
          'I will use these points to speak naturally about my academic purpose, why the program fits me, and how my education will be supported.',
          'I also want my answers to stay consistent when Officer Charles asks follow-up questions about my university, sponsor, future goals, and home-country plans.',
          'I want to speak about these points in a simple order so my answers remain steady when the officer asks follow-up questions.',
          'This story helps me remember the main points of my interview: my background, my school, my program, my sponsor, and my future plan.'
        ]
      : [
          'I want to explain my B1/B2 visitor visa story clearly using the travel details I have provided.',
          answerText ? `My main details are: ${answerText}` : 'My saved answers explain my background, travel purpose, trip details, funding, home ties, and return plan.',
          'I will use these points to speak naturally about why I am traveling, where I will go, how long I will stay, and how the trip will be paid for.',
          'I also want my answers to stay consistent when Officer Charles asks follow-up questions about my temporary purpose and my responsibilities at home.',
          'I want to explain these details in a simple order so my travel purpose, timing, funding, and return plan stay consistent.',
          'This story helps me remember my travel purpose, funding, home ties, and return plan before I begin a mock interview.'
        ];
    return this.validateStoryText(this.fitStoryLength(base.join(' ')));
  }

  validationError(message, metadata = {}) {
    return new AppError({
      statusCode: 502,
      publicMessage: 'AI story generation returned an invalid story. Please try again.',
      internalMessage: message,
      errorCode: ERROR_CODES.AI_RESPONSE_PARSE_ERROR,
      metadata
    });
  }

  unavailableError(error) {
    return new AppError({
      statusCode: 502,
      publicMessage: 'AI story generation is unavailable. Please try again.',
      internalMessage: error?.message || 'Interview story generation failed.',
      errorCode: ERROR_CODES.AI_PROVIDER_ERROR
    });
  }
}

module.exports = new InterviewStoryAIService();
module.exports.InterviewStoryAIService = InterviewStoryAIService;
